# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "PySpawnResult",
    "py_apply_cgroup_limits",
    "py_apply_landlock",
    "py_apply_seccomp_filter",
    "py_build_seccomp_bpf",
    "py_cgroup_add_process",
    "py_cgroup_v2_available",
    "py_check_new_mount_api",
    "py_cleanup_cgroup",
    "py_convert_cpu_shares",
    "py_create_cgroup",
    "py_drop_capabilities",
    "py_landlock_abi_version",
    "py_mount_overlay",
    "py_pidfd_is_alive",
    "py_pidfd_open",
    "py_pidfd_send_signal",
    "py_process_madvise_cold",
    "py_spawn_sandbox",
]

@typing.final
class PySpawnResult:
    r"""
    Result of spawning a sandbox process.
    """
    @property
    def pid(self) -> builtins.int:
        r"""
        PID of the sandbox shell process.
        """
    @property
    def stdin_fd(self) -> builtins.int:
        r"""
        File descriptor for writing to the shell's stdin.
        """
    @property
    def stdout_fd(self) -> builtins.int:
        r"""
        File descriptor for reading the shell's stdout.
        """
    @property
    def signal_r_fd(self) -> builtins.int:
        r"""
        File descriptor for reading the signal pipe (exit codes).
        """
    @property
    def signal_w_fd_num(self) -> builtins.int:
        r"""
        The fd number of the signal write end *inside* the child process.
        """
    @property
    def master_fd(self) -> typing.Optional[builtins.int]:
        r"""
        PTY master fd (only set when tty=True).
        """
    @property
    def pidfd(self) -> typing.Optional[builtins.int]:
        r"""
        pidfd for the shell process (None if kernel doesn't support it).
        """
    @property
    def err_r_fd(self) -> builtins.int:
        r"""
        Read end of the error/warning pipe from child init.
        After startup, Python reads this for non-fatal warnings.
        """

def py_apply_cgroup_limits(cgroup_path: builtins.str, limits: typing.Mapping[builtins.str, builtins.str]) -> None:
    r"""
    Apply resource limits to a cgroup.
    """

def py_apply_landlock(read_paths: typing.Optional[typing.Sequence[builtins.str]] = None, write_paths: typing.Optional[typing.Sequence[builtins.str]] = None, allowed_tcp_ports: typing.Optional[typing.Sequence[builtins.int]] = None, strict: builtins.bool = False) -> builtins.bool:
    r"""
    Apply Landlock filesystem + network restrictions.
    """

def py_apply_seccomp_filter() -> None:
    r"""
    Apply seccomp-bpf filter. Raises OSError on failure.
    """

def py_build_seccomp_bpf() -> bytes:
    r"""
    Build seccomp BPF bytecode as raw bytes.
    """

def py_cgroup_add_process(cgroup_path: builtins.str, pid: builtins.int) -> None:
    r"""
    Move a process into a cgroup.
    """

def py_cgroup_v2_available() -> builtins.bool:
    r"""
    Check if cgroup v2 is available.
    """

def py_check_new_mount_api() -> builtins.bool:
    r"""
    Check if kernel supports new mount API with lowerdir+ (>= 6.8).
    """

def py_cleanup_cgroup(cgroup_path: builtins.str) -> None:
    r"""
    Kill all processes in a cgroup and remove it.
    """

def py_convert_cpu_shares(shares: builtins.int) -> builtins.int:
    r"""
    Convert Docker CPU shares to cgroup v2 weight.
    """

def py_create_cgroup(name: builtins.str) -> builtins.str:
    r"""
    Create a cgroup for the sandbox. Returns the cgroup path.
    """

def py_drop_capabilities(extra_keep: typing.Optional[typing.Sequence[builtins.int]] = None) -> builtins.int:
    r"""
    Drop capabilities except Docker defaults + extra_keep.
    """

def py_landlock_abi_version() -> builtins.int:
    r"""
    Query kernel Landlock ABI version (0 if unavailable).
    """

def py_mount_overlay(lowerdir_spec: builtins.str, upper_dir: builtins.str, work_dir: builtins.str, target: builtins.str) -> None:
    r"""
    Mount overlayfs, auto-selecting new mount API or legacy mount(2).
    """

def py_pidfd_is_alive(pidfd: builtins.int) -> builtins.bool:
    r"""
    Check if process behind pidfd is alive.
    """

def py_pidfd_open(pid: builtins.int) -> typing.Optional[builtins.int]:
    r"""
    Create a pidfd for the given PID. Returns fd or None.
    """

def py_pidfd_send_signal(pidfd: builtins.int, sig: builtins.int) -> builtins.bool:
    r"""
    Send signal to process via pidfd. Returns True on success.
    """

def py_process_madvise_cold(pidfd: builtins.int) -> builtins.bool:
    r"""
    Hint kernel to reclaim (swap out) sandbox process memory via MADV_COLD.
    """

def py_spawn_sandbox(config: typing.Mapping[builtins.str, typing.Any]) -> PySpawnResult:
    r"""
    Spawn a sandbox process. Takes a config dict, returns a PySpawnResult.
    """

