/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/opensage-agent/nitrobox/go/cshared */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 10 "exports.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void NbxSetCoreBin(char* path);
extern void NbxFree(char* p);
extern int NbxCheckNewMountAPI(void);
extern char* NbxMountOverlay(char* lowerdirSpec, char* upperDir, char* workDir, char* target);
extern char* NbxBindMount(char* source, char* target);
extern char* NbxRbindMount(char* source, char* target);
extern char* NbxMakePrivate(char* target);
extern char* NbxRemountROBind(char* target);
extern char* NbxUmount(char* target);
extern char* NbxUmountLazy(char* target);
extern char* NbxUmountRecursiveLazy(char* target);
extern int NbxCgroupV2Available(void);
extern char* NbxCreateCgroup(char* name, char** outPath);
extern char* NbxApplyCgroupLimits(char* cgroupPath, char* limitsJSON);
extern char* NbxCgroupAddProcess(char* cgroupPath, unsigned int pid);
extern char* NbxCleanupCgroup(char* cgroupPath);
extern long unsigned int NbxConvertCPUShares(long unsigned int shares);
extern int NbxPidfdOpen(int pid, int* outFd);
extern int NbxPidfdSendSignal(int pfd, int sig);
extern int NbxPidfdIsAlive(int pfd);
extern int NbxProcessMadviseCold(int pfd);
extern char* NbxFuserKill(char* targetPath, unsigned int* outCount);
extern char* NbxQmpSend(char* socketPath, char* commandJSON, long unsigned int timeoutSecs, char** outResp);
extern char* NbxConvertWhiteouts(char* layerDir, int useUserXattr, unsigned int* outCount);
extern char* NbxParseImageRef(char* image, char** outDomain, char** outRepo, char** outTag);
extern unsigned int NbxLandlockABIVersion(void);
extern void NbxBuildSeccompBPF(void** outBuf, int* outLen);
extern char* NbxApplySeccompFilter(void);
extern char* NbxDropCapabilities(char* extraKeepJSON, char* extraDropJSON, unsigned int* outDropped);
extern char* NbxApplyLandlock(char* readPathsJSON, char* writePathsJSON, char* portsJSON, int strict, int* outApplied);
extern char* NbxUsernFixupForDelete(int usernsPid, char* dirPath, unsigned int* outCount);
extern char* NbxSpawnSandbox(char* configJSON, char** outResultJSON);

#ifdef __cplusplus
}
#endif
